### ISSUE TITLE
NoScript appearing to block a specific site when not configured to, even when restrictions are disabled globally.

### ISSUE THREAD

**Issue by NevanNedall** [hackademix/noscript#386]
I'm not exactly sure what I did, I was reaching to open a new tab and mis-pressed something involving Ctrl + Y and when I did, my no script for youtube.com got set to custom and the "match HTTPS only" lock turned red.
Ever since then, after trying to revert those to how they were originally, resetting noscript to default, reinstalling noscript, no matter what I do youtube videos look like this for me now when noscript is installed and enabled:
![image](https://github.com/user-attachments/assets/57d41d0b-0474-4584-ba6b-3a556df0057a)

Both the audio and video play underneath, and I can dismiss the overlay.

**Comment by NevanNedall** [comment]
Resolved.
Cleared cache/cookies a second time, first time didn't do the trick for some reason.
Sorry about that.

**Comment by NevanNedall** [comment]
Nevermind- when I logged back in, it started happening again.

**Comment by hackademix** [comment]
Thank you for your report.

1. Which NoScript and browser version are you using exactly?
2. Could you please share your _NoScript Options>Export_ file?

**Comment by YellowRoseCx** [comment]
i also just started having this issue
NoScript Version - 12.0.0
Brave Browser - Version 1.73.89 Chromium: 131.0.6778.69 (Official Build) (64-bit)


even when I use "Reset" and then "Disable restrictions globally (dangerous)" and go to Youtube, I have the NoScript popup blocking the video previews but still having the video play underneath

 
![image](https://github.com/user-attachments/assets/8017233d-2f22-4949-8cec-20852b67f494)


Also happens if I trust it and enable all the site capabilities

**Comment by hackademix** [comment]
Investigating, thanks.

In the meanwhile rolled back in the Chrome store to 11.4.42, relabeled as 12.0.0.1 because of Google's "higher version" requirement for rollback.

**Comment by YellowRoseCx** [comment]
Thank you!

**Comment by hackademix** [comment]
This should be fixed by 12.0.1, thanl you.

**Comment by YellowRoseCx** [comment]
> This should be fixed by 12.0.1, thanl you.

Thanks! What was the code that was changed to fix it?

**Comment by hackademix** [comment]
> Thanks! What was the code that was changed to fix it?

https://github.com/hackademix/nscl/commit/eb866bccb0b9cb40ee45be94077ab5c6e1395a7e
