### ISSUE TITLE
Regression: v12.0.1 ignores 'top-level trusted' setting

### ISSUE THREAD

**Issue by mamins1376** [hackademix/noscript#388]
Since I had automatic extensions update enabled in my browser, noticed the current latest version started blocking top-level scripts too, regardless of my preference. Tried reinstalling the extension, export-reimport config, and manually toggling the option may times. Seemed to be a regression.

So I removed the webstore version and installed the extension manually (via [the link on your homepage](https://secure.informaction.com/download/betas/noscript-11.4.44rc2-chrome.zip), v11.4.44rc2) and started working when imported my config.

Browser: Chromium Version 131.0.6778.69 (Official Build) Arch Linux (64-bit)

**Comment by RonnyTNL** [comment]
Can confirm, tried multiple machines with multiple chromium browsers 12.0.1 broke this feature. (Win10x64)

**Comment by hackademix** [comment]
Confirmed. Fixing it in 12.0.2, to be released ASAP. Thank you for reporting.

**Comment by mushu999** [comment]
Verified. The latest NoScript blocked all access to my local LAN websites (that happen to not use SSL certs) (Plex, Synology NAS, Pi-Hole, etc) and nothing I could do would enable access until I removed the NoScript extension. So I installed the version per the link given above and now everything works again.

EDIT: wish I had thought to save my settings first...ugh..

**Comment by gpouliot77** [comment]
Using "Disable Restrictions for this tab" temporarily resolves the problem.

Edit:  It's not that great though, going between pages on the same site may require you to turn the "Disable restrictions for this tab" feature off and on again.

**Comment by SynapseScribe** [comment]
this update broke the whole fkn internet for me on brave. also why isn't there a release for this version in releases?

**Comment by micisse** [comment]
On **brave** too, even **localhost** sites have trouble. It happens when you least expect it, and it wasn't easy to identify.

**Comment by hackademix** [comment]
This is fixed in [12.0.2](https://noscript.net/getit/#nonstore-versions-for-chromium), which is already in queue for approval on the Chrome store. Thank you for your reports.

**Comment by jw4791** [comment]
This regression appears to still break sites after enabling "Temporarily set top-level sites to TRUSTED". I see the problem even with whitelisted sites now.

The temp fix is to toggle "Disable Restrictions for this tab" on and off.

**Comment by hackademix** [comment]
> This regression appears to still break

Nope, this one appears to be actually fixed. Your problem is most likely a side effect of #390 (Vivaldi only, so far).

**Comment by SynapseScribe** [comment]
12.0.2 works for me too now again on brave. thank you for fast bugfix

**Comment by RonnyTNL** [comment]
@hackademix this issue is still not fully resolved, since this broken update while being on 12.08 + brave x64 every about 1 in 10 websites I need to reload the page for it to work as expected. the Icon does not show that it's blocking, but the page isn't rendering correctly or not displaying anything at all.

Just haven't found stable reproduction yet :-/

**Comment by inspector71** [comment]
Unfortunately this issue is still a problem for me.

All top level domains set to 'Custom' which, as was *charmingly* referenced in a previous thread, effectively "breaks the ... internet" for me.

Thing is, I do not recall having this issue until the last month or so. Whereas this issue was originally raised in 2024 (and it's now late May 2025).

BTW,  I want to be as helpful as I can. Hence this edit. UA string (unmodified, ESR):

`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0`

NoScript version:

`13.0.6`

Anything else I can do?

**Comment by SynapseScribe** [comment]
> Unfortunately this issue is still a problem for me.
> 
> All top level domains set to 'Custom' which, as was _charmingly_ referenced in a previous thread, effectively "breaks the ... internet" for me.
> 
> Thing is, I do not recall having this issue until the last month or so. Whereas this issue was originally raised in 2024 (and it's now late May 2025).
> 
> BTW, I want to be as helpful as I can. Hence this edit. UA string (unmodified, ESR):
> 
> `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0`
> 
> NoScript version:
> 
> `13.0.6`
> 
> Anything else I can do?

i am the charming guy. i remember giving noscript another shot after the claiming that the issues were fixed, but was still not working as expected, so i ended up returning to good old umatrix even if it is obsoleted. on firefox, however there is a fork numatrix which is being updated.

**Comment by hackademix** [comment]
> All top level domains set to 'Custom' which, as was _charmingly_ referenced in a previous thread, effectively "breaks the ... internet" for me.

They're set to CUSTOM because the permissions are contextual (i.e. applied to sub-resources as long as they match the top level document's origin), but  those permissions are the very same granted for TRUSTED. 

Therefore this shouldn't "break the ... internet" but provide some nicer security properties.

The rationale for this change in behavior is explained in #417 , and it's definitely different from this (closed) bug, unless I'm misunderstanding your report.
